config-version: 2

name: 'facebook_ads_metrics'
version: '1.0.0'


require-dbt-version: [">=1.0.0", "<2.0.0"]

#add custom schema by removing comment
#profile: 'your custom profile'

models:
  facebook_ads_metrics:
     +materialized: table

vars:
  #remove the comment to use custom schemas
  #facebook_ads_schema: YOUR_CUSTOM_SCHEMA
  #facebook_ads_database: YOUR CUSTOM_DATABASE

  facebook_ads_metrics:
    #toggle is set to true to only include recent records of a particular ad, adset
    #and campaign and exclude previous versions. This is beneficial when you don't want to mix your old test campaigns 
    #with your fresh campaigns
    is_most_recent_toggle: 'TRUE'
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    
